#!/usr/bin/env python3
"""Generate signal-log INDEX.md from entry frontmatter. Entries are the SoT.

The ledger used to be hand-edited, so it drifted: on 2026-08-09 it listed 5 of
12 entries in the doc-corpus map and carried two statuses that existed nowhere
else. This regenerates it from `entries/*.md` so that class of drift is gone.

  python3 scripts/signal_log_index.py            # CHECK mode (no flag): diff only, exit 1 if stale
  python3 scripts/signal_log_index.py --write    # rewrite INDEX.md
"""
from __future__ import annotations

import argparse
import difflib
import os
import re
import sqlite3
import sys
from pathlib import Path
from urllib.parse import urlparse

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit(
        "PyYAML required. Use: ~/Documents/T1000/venv/bin/python "
        "scripts/signal_log_index.py"
    )

ROOT = Path(__file__).resolve().parents[1]
LOG = ROOT / "docs" / "research" / "signal-log"
ENTRIES = LOG / "entries"
INDEX = LOG / "INDEX.md"

PREAMBLE = """# Signal log index

Newest first. Full text in `entries/`. Open steals rollup: [`STEALS.md`](STEALS.md). Process: [`README.md`](README.md).

<!-- GENERATED by scripts/signal_log_index.py from entries/*.md frontmatter. Do not hand-edit: edit the entry, then re-run with --write. -->

|| ID | Date | Title | Bucket | Posture | Rank | Entry | Source | Status |
||----|------|-------|--------|---------|------|-------|--------|--------|
"""

REQUIRED = ("id", "date", "title", "source_url", "bucket", "posture", "steal_rank", "status")

# Enums are advisory here: warn, never drop a row. Silent omission is the exact
# failure this script exists to kill.
BUCKETS = {"harness", "inference", "models", "router", "ops", "product", "noise"}
POSTURES = {"watch", "steal", "spike", "adopt", "ignore"}
RANKS = {"P0", "P1", "P2", "—"}
STATUSES = {"open", "carded", "wired", "done", "wont"}

FM_RE = re.compile(r"^```yaml\n(.*?)^```", re.S | re.M)


def parse(path: Path) -> tuple[dict | None, list[str]]:
    warn: list[str] = []
    m = FM_RE.search(path.read_text())
    if not m:
        return None, [f"{path.name}: no ```yaml frontmatter block"]
    try:
        fm = yaml.safe_load(m.group(1))
    except yaml.YAMLError as e:
        return None, [f"{path.name}: unparseable yaml — {e}"]
    if not isinstance(fm, dict):
        return None, [f"{path.name}: frontmatter is not a mapping"]

    missing = [k for k in REQUIRED if not fm.get(k)]
    if missing:
        return None, [f"{path.name}: missing required field(s): {', '.join(missing)}"]

    for field, allowed in (
        ("bucket", BUCKETS), ("posture", POSTURES),
        ("steal_rank", RANKS), ("status", STATUSES),
    ):
        if str(fm[field]) not in allowed:
            warn.append(f"{fm['id']}: {field}={fm[field]!r} not in {sorted(allowed)}")

    fm["_file"] = path.name
    return fm, warn


def label_for(url: str) -> str:
    host = (urlparse(url).hostname or "").lower()
    if host.endswith("github.com"):
        return "repo"
    if host.endswith("arxiv.org"):
        return "arXiv"
    if host.endswith("huggingface.co"):
        return "HF"
    return "docs"


def source_cell(fm: dict) -> str:
    parts = [f"[src]({fm['source_url']})"]
    if fm.get("source_url_2"):
        parts.append(f"[src2]({fm['source_url_2']})")
    for key in fm.get("index_links") or []:
        url = fm.get({"repo": "canonical_repo", "docs": "canonical_docs"}.get(key, key))
        if url:
            parts.append(f"[{label_for(url)}]({url})")
    return " · ".join(parts)


def date_cell(fm: dict) -> str:
    if not fm.get("updated"):
        return str(fm["date"])
    upd = str(fm["updated"])[5:]  # MM-DD
    return f"{fm['date']} · **upd {upd}**"


def row(fm: dict) -> str:
    status = f"**{fm['status_note']}**" if fm.get("status_note") else str(fm["status"])
    return (
        f"| {fm['id']} | {date_cell(fm)} | {fm.get('index_title') or fm['title']} | "
        f"`{fm['bucket']}` | `{fm['posture']}` | `{fm['steal_rank']}` | "
        f"[entry](entries/{fm['_file']}) | {source_cell(fm)} | {status} |\n"
    )

def build() -> tuple[str, list[str], int]:
    warn: list[str] = []
    rows: list[dict] = []
    for p in sorted(ENTRIES.glob("SIG-*.md")):
        fm, w = parse(p)
        warn.extend(w)
        if fm:
            rows.append(fm)
    # id is SIG-YYYYMMDD-NN, so reverse lexicographic == newest first
    rows.sort(key=lambda f: str(f["id"]), reverse=True)
    return PREAMBLE + "".join(row(f) for f in rows), warn, len(rows)

# ---------------------------------------------------------------------------
# Measurement extraction and verification against kanban cards
# ---------------------------------------------------------------------------

def extract_measurements(fm: dict) -> dict[str, str]:
    """Return a mapping of measurement fields present in frontmatter.
    Currently only looks for a ``result`` field but can be extended."""
    if fm.get("result"):
        return {"result": str(fm["result"]).strip()}
    return {}

def collect_measurements() -> dict[str, dict]:
    """Collect measurements for all entries keyed by entry id."""
    meas: dict[str, dict] = {}
    for p in ENTRIES.glob("SIG-*.md"):
        fm, _ = parse(p)
        if not fm:
            continue
        data = extract_measurements(fm)
        if data:
            meas[fm["id"]] = data
    return meas

def verify_against_cards(meas: dict[str, dict], warn: list[str]) -> None:
    """For each entry with a measurement, ensure any related kanban card (status != open/ready)
    contains the same ``result`` value.
    Adds warnings to *warn* for mismatches.
    """
    db_path = os.getenv(
        "HERMES_KANBAN_DB",
        os.path.join(os.getenv("HERMES_HOME", "~/.t1000"), "kanban", "boards", "steals", "kanban.db"),
    )
    db_path = os.path.expanduser(db_path)
    if not os.path.isfile(db_path):
        warn.append(f"Kanban DB not found at {db_path}; cannot verify measurements.")
        return

    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    for entry_id, data in meas.items():
        # Find cards that mention the entry id and are not open/ready
        cur.execute(
            "SELECT id, result FROM tasks WHERE body LIKE ? AND status NOT IN ('open','ready')",
            (f"%{entry_id}%",),
        )
        rows = cur.fetchall()
        for card_id, card_result in rows:
            if not card_result or card_result.strip() != data.get("result"):
                warn.append(
                    f"{card_id}: measurement mismatch for {entry_id} – card result missing or differs"
                )
    conn.close()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true", help="rewrite INDEX.md (default is --check)")
    args = ap.parse_args()

    if not ENTRIES.is_dir():
        print(f"no entries dir: {ENTRIES}", file=sys.stderr)
        return 2

    new, warn, n = build()
    # Collect and verify measurements against cards
    measurements = collect_measurements()
    verify_against_cards(measurements, warn)

    for w in warn:
        print(f"WARN {w}", file=sys.stderr)

    old = INDEX.read_text() if INDEX.exists() else ""
    if args.write:
        INDEX.write_text(new)
        print(f"wrote {INDEX} — {n} entries" + (" (unchanged)" if new == old else ""))
        return 0

    if new == old:
        print(f"INDEX.md up to date — {n} entries")
        return 0
    print(f"INDEX.md STALE — {n} entries in entries/. Re-run with --write.\n", file=sys.stderr)
    sys.stderr.writelines(
        difflib.unified_diff(
            old.splitlines(keepends=True), new.splitlines(keepends=True),
            fromfile="INDEX.md (on disk)", tofile="INDEX.md (generated)",
        )
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
